WebixJet. First task
AndreyShpakXB/jet-start pull request #1
Opened 2021-10-01 06:38 UTC by AndreyShpakXB

2021-10-01 07:15 UTC, VeraOrekhXB requested changes

2021-10-01 07:15 UTC, VeraOrekhXB commented on sources/views/datatable.js
> +		const obj = this._dataItems.data.pull[1];
В случае, если в коллекции не будет данных с id равным 1, вылетит ошибка

2021-10-01 07:15 UTC, VeraOrekhXB commented on sources/views/datatable.js
> +				this.$scope.getRoot().queryView({ localId:"form" }).save();
Можно использовать this.$scope.$$('form')
Касается всех queryView в этом файле
Ещё для часто используемых вьюшек можно добавить геттеры, чтобы каждый раз, когда тебе нужна вьюшка, не искать в коде её id + меньше вероятность того, что ты допустишь опечатку в идентификаторе

2021-10-01 07:15 UTC, VeraOrekhXB commented on sources/views/datatable.js
> +		view.queryView({ localId:"table" }).parse(this._dataItems);
Если одна и та же вьюшка используется несколько раз, то стоит сохранить её значение в переменной

2021-10-01 07:15 UTC, VeraOrekhXB commented on sources/views/datatable.js
> +		view.queryView({ localId:"form" }).bind(view.queryView({localId:"table"}));
При переключении между Data, Contacts & Settings и обратно на Data, изменения отображаются в том же виде, что и были сразу после изменения.
Но если удалить строку из любой таблицы, то при повторном переходе на вкладку Data удалённые строки снова появляются

2021-10-01 16:28 UTC, HelgaListopad requested changes

2021-10-01 16:28 UTC, HelgaListopad commented on sources/views/datatable.js
> +		const obj = this._dataItems.data.pull[1];
Да и данных тут хорошо бы дождаться - если работаешь с данными, лучше всегда учитывать этот момент.

Есть два варианта, как это можно переделать 
- (простой) отказаться от генерируемой формы и просто всё захардкодить на этом этапе, используя массивы данных вместо коллекций
- (интересный) правильно привязаться к загржаемым данным и дождаться из через [`waitData`](https://docs.webix.com/api__link__datacollection_waitdata_other.html)

Пример интересного: https://snippet.webix.com/6nkew5pg
`config()` может возвращать как просто конфигурацию UI (объект), так и промис с конфигом
Документация: https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/asynchronous-views

Я приму любой из этих вариантов.

2021-10-01 16:28 UTC, HelgaListopad commented on sources/views/datatable.js
> +		view.queryView({ localId:"form" }).bind(view.queryView({localId:"table"}));
Мы говорили об этом сегодня на лекции, добавлю и сюда - при синхронизации **таблицы с коллекцией** лучше отказаться от биндинга **формы с таблицей**.
`add`/`updateItem`/`remove` должны вызываться на коллекции (на мастере, с которым мы синхронизируемся).
Именно то, что форма добавляет новую строку в таблицу, а не на коллекцию, даёт эту проблему

2021-10-03 11:37 UTC, VeraOrekhXB approved these changes

2021-10-03 18:09 UTC, HelgaListopad approved these changes

2021-10-03 18:11 UTC, merged