Webix-Jet. Lesson 3 - Practice.
AndreyShpakXB/jet-start pull request #3
Opened 2021-10-04 20:40 UTC by AndreyShpakXB

2021-10-05 05:10 UTC, VeraOrekhXB requested changes

2021-10-05 05:10 UTC, VeraOrekhXB commented on sources/views/contacts/list.js
> +							`<div> ${dCountry} ${dStatus} <span class='webix_icon wxi-trash' style='float:right;'></span></div>`;
Шаблонные строки многострочные
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#multi-line_strings

2021-10-05 11:08 UTC, VeraOrekhXB approved these changes

2021-10-05 12:08 UTC, HelgaListopad requested changes
Сохранение данных необходимо переписать с самостоятельных запросов на save коллекции

2021-10-05 12:08 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +		webix.ajax().post(URLs.urlContacts, values, (result) => {
А есть причина, по которой данные сохраняются вручную, а не через save коллекции?
С префиксом `"rest->"` (несколько раз встречался в лекциях) сохранение будет идти с нужными методами запросов

2021-10-05 12:08 UTC, HelgaListopad commented on sources/views/contacts/form.js
> +		webix.ajax().post(URLs.urlContacts, values, (result) => {
Поэтому ожидается скорее `collection.add`, обёрнутое в `waitSave`

2021-10-06 12:11 UTC, HelgaListopad approved these changes

2021-10-06 12:13 UTC, merged